server {
    listen 80;
    server_name  beijihunb.com;
    charset utf-8;
    location / {
      root /home/proxy_soft/proxy_web/dist;
      index index.html index.hml;
      try_files $uri $uri/ /index.html;
    }
}
